#### Performing Convolution using Scipy

In [1]:
from scipy.signal import convolve2d
import numpy as np

In [6]:

A = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
B = np.array([[0,1],[1,0]])

x = convolve2d(A, B, mode='valid')
x


array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

#### Convolution without overlapping

In [7]:
output = np.zeros((2,2))

for i in range(0, 4,2):
    for j in range(0, 4,2):
        region = A[i:i+2, j:j+2]
        output[i//2, j//2] = np.sum(region * B)

output

array([[0., 0.],
       [0., 0.]])

In [10]:
def conv_without_overlap(x, y, stride):
    kernel_size = y.shape[0]
    out_rows = x.shape[0]//stride
    out_cols = x.shape[1]//stride
    o = np.zeros((out_rows, out_cols))

    for a in range(0, x.shape[0] - kernel_size + 1, stride):
        for b in range(0, x.shape[1] - kernel_size + 1, stride):
            r = x[a:a+kernel_size, b:b+kernel_size]
            o[a//stride, b//stride] = np.sum(r * y)
    return o

In [9]:
A = np.array([[1,0,0,0,0,0],
              [0,1,0,0,0,0],
              [0,0,1,0,0,0],
              [0,0,0,1,0,0],
              [0,0,0,0,1,0],
              [0,0,0,0,0,1]])
B = np.array([[0,0,1],
              [0,1,0],
              [1,0,0]])

print(conv_without_overlap(A, B, 3))

[[1. 0.]
 [0. 1.]]
